### PR TITLE
More compact code

### PR DESCRIPTION
**Pull request by frederic-mahe**
This is merely a suggestion. No need to write the downloaded script to mass storage, you can execute it directly.

### CODE REVIEW

**Comment by theypsilon** [comment]
Just one little thing to  point out. /tmp is not mass storage in MiSTer, as it is mounted in RAM. Piping a script into bash works, but messes with the ${0} and other variables, that's why I consider it a less ideal solution than calling the script normally.

**Comment by frederic-mahe** [comment]
I see, thanks for the info. Then, what about skipping the `chmod +x bios-getter.sh` and executing the file directly (`bash bios-getter.sh`)? That should not alter `${0}`.

Again, these are merely suggestions, I hope I am not annoying you, I just really like to review code, that's all.

**Comment by theypsilon** [comment]
No is actually the opposite, I think your suggestions are very valuable. I hope to keep seeing you around. I've tested these changes and they are good to merge.

**Comment by frederic-mahe** [comment]
thanks!

**Comment by MAME-GETTER** [comment]
@frederic-mahe your suggestions are very welcomed, Thankyou! 
All of your retro gaming github projects are legendary.  love the SM Rompacks and NT Jailbreaks you host.

**Pull request merged**
