### PR TITLE
Add bsx_bios.rom options

### PR DESCRIPTION
**Pull request by birdybro**
Untested as of now, but basically will add the BSX_BIOS and a good structure for use. Default will be the BS-X project's English+NoDRM, with folders for other options.

Ignore the readme changes, I goofed on branches from other PR :P

### CODE REVIEW

**Comment by MAME-GETTER** [comment]
I need time to look at this. May need to move your repo to our standard one
on Archive.org

**Comment by birdybro** [comment]
Yup, is more of a proposal of how to do it, hopefully to save you time developing it yourself. I might test out the roms when I get home and see how they all work. The ones with DRM might not be worth using, for instance.

**Comment by birdybro** [comment]
Yeah tested at home, doesn't work, but I will submit this as draft on the main one, since I forgot that this repo was deprecated.

**Comment by theypsilon** [comment]
Thanks @birdybro , I added it to the script right now. Your code was of good help.

**Pull request closed without merging**
