### PR TITLE
add gba bios

### PR DESCRIPTION
**Pull request by badatgamespanda**

### CODE REVIEW

**Comment by MAME-GETTER** [comment]
This is great that you added this PR, I am going to move the bios from: 

https://archive.org/download/gba_20200705/GBA.zip

to the rest of the bios pack as this will make it easier to manage and for others to inspect.

**Comment by MAME-GETTER** [comment]
@badatgamespanda please change the PR to Download from this location:

https://archive.org/download/mi-ster-console-bios-pack/MiSTer_Console_BIOS_PACK.zip/GBA.zip

**Comment by MAME-GETTER** [comment]
I have also confirmed the checksum for the bios and it looks fine as I see other matching online. 

```
amoore@amoore-OptiPlex-7010:~/Downloads$ crc32 gba_bios.bin
81977335

```

**Comment by badatgamespanda** [comment]
Download url has been updated. I figured you would want to merge it into the current pack. I'm not sure if it's much different but I also have the Japan debug bios we can add to the pack for anyone who wants to check it out.

**Comment by MAME-GETTER** [comment]
@badatgamespanda hit me up on discord

**Pull request merged**
